/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundPerformanceRouteImport } from './routes/fund-performance'
import { Route as IndustryOverviewRouteImport } from './routes/industry-overview'
import { Route as InvestorAnalyticsRouteImport } from './routes/investor-analytics'
import { Route as SipMarketTrendsRouteImport } from './routes/sip-market-trends'
import { Route as FundsFundIdRouteImport } from './routes/funds.$fundId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundPerformanceRoute = FundPerformanceRouteImport.update({
  id: '/fund-performance',
  path: '/fund-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryOverviewRoute = IndustryOverviewRouteImport.update({
  id: '/industry-overview',
  path: '/industry-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorAnalyticsRoute = InvestorAnalyticsRouteImport.update({
  id: '/investor-analytics',
  path: '/investor-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SipMarketTrendsRoute = SipMarketTrendsRouteImport.update({
  id: '/sip-market-trends',
  path: '/sip-market-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsFundIdRoute = FundsFundIdRouteImport.update({
  id: '/funds/$fundId',
  path: '/funds/$fundId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fund-performance': typeof FundPerformanceRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/investor-analytics': typeof InvestorAnalyticsRoute
  '/sip-market-trends': typeof SipMarketTrendsRoute
  '/funds/$fundId': typeof FundsFundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fund-performance': typeof FundPerformanceRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/investor-analytics': typeof InvestorAnalyticsRoute
  '/sip-market-trends': typeof SipMarketTrendsRoute
  '/funds/$fundId': typeof FundsFundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fund-performance': typeof FundPerformanceRoute
  '/industry-overview': typeof IndustryOverviewRoute
  '/investor-analytics': typeof InvestorAnalyticsRoute
  '/sip-market-trends': typeof SipMarketTrendsRoute
  '/funds/$fundId': typeof FundsFundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fund-performance'
    | '/industry-overview'
    | '/investor-analytics'
    | '/sip-market-trends'
    | '/funds/$fundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fund-performance'
    | '/industry-overview'
    | '/investor-analytics'
    | '/sip-market-trends'
    | '/funds/$fundId'
  id:
    | '__root__'
    | '/'
    | '/fund-performance'
    | '/industry-overview'
    | '/investor-analytics'
    | '/sip-market-trends'
    | '/funds/$fundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundPerformanceRoute: typeof FundPerformanceRoute
  IndustryOverviewRoute: typeof IndustryOverviewRoute
  InvestorAnalyticsRoute: typeof InvestorAnalyticsRoute
  SipMarketTrendsRoute: typeof SipMarketTrendsRoute
  FundsFundIdRoute: typeof FundsFundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund-performance': {
      id: '/fund-performance'
      path: '/fund-performance'
      fullPath: '/fund-performance'
      preLoaderRoute: typeof FundPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-overview': {
      id: '/industry-overview'
      path: '/industry-overview'
      fullPath: '/industry-overview'
      preLoaderRoute: typeof IndustryOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-analytics': {
      id: '/investor-analytics'
      path: '/investor-analytics'
      fullPath: '/investor-analytics'
      preLoaderRoute: typeof InvestorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip-market-trends': {
      id: '/sip-market-trends'
      path: '/sip-market-trends'
      fullPath: '/sip-market-trends'
      preLoaderRoute: typeof SipMarketTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/$fundId': {
      id: '/funds/$fundId'
      path: '/funds/$fundId'
      fullPath: '/funds/$fundId'
      preLoaderRoute: typeof FundsFundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundPerformanceRoute: FundPerformanceRoute,
  IndustryOverviewRoute: IndustryOverviewRoute,
  InvestorAnalyticsRoute: InvestorAnalyticsRoute,
  SipMarketTrendsRoute: SipMarketTrendsRoute,
  FundsFundIdRoute: FundsFundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
