// Dashboard data fetching and caching layer
// Loads data from frontend/public/api/dashboard_data.json (generated by backend)

import type {
  KpiData,
  AumTrend,
  AmcAum,
  FundRow,
  NavSeries,
  StateTransaction,
  TransactionSplit,
  AgeGroupSip,
  MonthlyVolume,
  SipVsMarket,
  CategoryInflow,
  FundCategory,
  FundHouse,
  FundPlan,
} from "./dashboard-types";
import { ALL } from "./dashboard-types";

export { ALL } from "./dashboard-types";

// Data source metadata
export const IS_LIVE_DATA = true; // Set to false if using mock data
export const DATA_SOURCE_LABEL = "Real backend data";

// In-memory cache for raw data
let cachedData: any = null;

/**
 * Fetch raw dashboard data from the JSON API endpoint
 */
async function fetchDashboardData() {
  if (cachedData) {
    return cachedData;
  }

  try {
    const response = await fetch("/api/dashboard_data.json");
    if (!response.ok) {
      throw new Error(`Failed to fetch dashboard data: ${response.status}`);
    }
    cachedData = await response.json();
    return cachedData;
  } catch (error) {
    console.error("Error fetching dashboard data:", error);
    throw error;
  }
}

// ============================================================================
// INDUSTRY OVERVIEW (Page 1)
// ============================================================================

export async function getIndustryKpis(): Promise<KpiData> {
  const data = await fetchDashboardData();
  return data.kpis || {};
}

export async function getIndustryAumTrend(): Promise<AumTrend[]> {
  const data = await fetchDashboardData();
  return data.aumTrend || [];
}

export async function getAumByAmc(): Promise<AmcAum[]> {
  const data = await fetchDashboardData();
  return data.aumByAmc || [];
}

// ============================================================================
// FUND PERFORMANCE (Page 2)
// ============================================================================

export async function getFunds(
  fundHouse?: string,
  category?: string,
  plan?: string
): Promise<FundRow[]> {
  const data = await fetchDashboardData();
  let funds: FundRow[] = data.funds || [];

  if (fundHouse && fundHouse !== ALL) {
    funds = funds.filter((f) => f.fundHouse === fundHouse);
  }
  if (category && category !== ALL) {
    funds = funds.filter((f) => f.category === category);
  }
  if (plan && plan !== ALL) {
    funds = funds.filter((f) => f.plan === plan);
  }

  return funds;
}

export async function getFundHouses(): Promise<FundHouse[]> {
  const data = await fetchDashboardData();
  return data.fundHouses || [];
}

export async function getCategories(): Promise<FundCategory[]> {
  const data = await fetchDashboardData();
  return data.categories || [];
}

export async function getNavSeries(amfiCode: string): Promise<NavSeries[]> {
  const data = await fetchDashboardData();
  const navMap = data.navSeriesMap || {};
  return navMap[amfiCode] || [];
}

export async function fetchFundById(amfiCode: string): Promise<FundRow | null> {
  const funds = await getFunds();
  return funds.find((f) => f.amfiCode === amfiCode) || null;
}

// ============================================================================
// INVESTOR ANALYTICS (Page 3)
// ============================================================================

export const AGE_GROUPS = ["18-25", "26-35", "36-45", "46-55", "56-65", "65+"];

export async function getTransactionByState(
  cityTier?: string,
  ageGroup?: string
): Promise<StateTransaction[]> {
  const data = await fetchDashboardData();
  let transactions: StateTransaction[] = data.stateAmounts || [];

  if (cityTier && cityTier !== ALL) {
    const cityTierData = data.stateAmountsByCityTier?.[cityTier];
    transactions = cityTierData || [];
  }

  if (ageGroup && ageGroup !== ALL) {
    const ageGroupData = data.stateAmountsByAgeGroup?.[ageGroup];
    transactions = ageGroupData || transactions;
  }

  return transactions;
}

export async function getTxnSplit(): Promise<TransactionSplit[]> {
  const data = await fetchDashboardData();
  return data.txnSplit || [];
}

export async function getStatesSync(): Promise<string[]> {
  const data = await fetchDashboardData();
  return data.states || [];
}

export async function getAgeGroupSip(state?: string): Promise<AgeGroupSip[]> {
  const data = await fetchDashboardData();
  if (state && state !== ALL) {
    return data.ageGroupSipByState?.[state] || [];
  }
  return data.ageGroupSip || [];
}

export async function getMonthlyVolume(): Promise<MonthlyVolume[]> {
  const data = await fetchDashboardData();
  return data.monthlyVolume || [];
}

// ============================================================================
// SIP & MARKET TRENDS (Page 4)
// ============================================================================

export async function getSipVsMarket(): Promise<SipVsMarket[]> {
  const data = await fetchDashboardData();
  return data.sipVsMarket || [];
}

export async function getCategoryInflowHeatmap(): Promise<CategoryInflow[]> {
  const data = await fetchDashboardData();
  return data.categoryInflowHeatmap || [];
}

export async function getTopCategoriesFy25(): Promise<CategoryInflow[]> {
  const data = await fetchDashboardData();
  return data.topCategoriesFy25 || [];
}

// ============================================================================
// UTILITIES
// ============================================================================

export function clearCache() {
  cachedData = null;
}

export async function validateDataIntegrity(): Promise<boolean> {
  try {
    const data = await fetchDashboardData();
    return (
      data.kpis &&
      data.aumTrend &&
      data.funds &&
      data.stateAmounts &&
      data.sipVsMarket !== undefined
    );
  } catch (error) {
    console.error("Data integrity validation failed:", error);
    return false;
  }
}
